name: 'Terraform Deploy with Managed Identity'

on:
  push:
    branches: ['master']

jobs:
  terraform:
    name: 'Terraform'
    # Use the label you assigned when setting up your self-hosted runner
    runs-on: self-hosted
    defaults:
      run:
        working-directory: Terraform-code

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
